ACCOUNTS=[
"GDZKLEYJ54QUIEYE4DUUOCIJDUS7R5MDW5MCAB3XTUGPJ3C7SSZJRQUC"
]
[DOCUMENTATION]
ORG_NAME="Vortexledger"
ORG_PHYSICAL_ADDRESS="No Republica"
[[PRINCIPALS]]
name="Arthur Pendragon"
[[CURRENCIES]]
code="ZSOZSO"
issuer="GDZKLEYJ54QUIEYE4DUUOCIJDUS7R5MDW5MCAB3XTUGPJ3C7SSZJRQUC"
is_asset_anchored=false
